name: pgadmin
services:
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: pgadmin4
    restart: always
    environment:
      # ALL supported environment variables:
      # https://www.pgadmin.org/docs/pgadmin4/8.10/container_deployment.html
      TZ: ${PGADMIN_TZ}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "15433:80"
    volumes:
      # servers config json examples
      # https://www.pgadmin.org/docs/pgadmin4/latest/import_export_servers.html#json-format
      - ./config/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./config/pgpass:/pgpass:rw # passwords for the connections in this file
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_cert_data:/certs
    depends_on:
      - postgres
    profiles: ["only-postgres", "all"]
