name: pgadmin
services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    restart: always
    depends_on:
      - postgres
    ports:
      - '15433:80'
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
      - ./config/pgpass:/pgpass:rw
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_cert_data:/certs
    environment:
      TZ: ${PGADMIN_TZ}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    profiles:
      - only-postgres
      - only-pgadmin
      - all
