name: mariadb
services:
    mariadb:
        image: mariadb:${MARIADB_VERSION}
        container_name: mariadb
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
          MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MARIADB_DATABASE}
          MYSQL_USER: ${MARIADB_USER}
          MYSQL_PASSWORD: ${MARIADB_PASSWORD}
        volumes:
            - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - mariadb_data:/var/lib/mysql
        ports:
            - 4306:3306
#    adminer:
#        container_name: adminer
#        image: adminer
#        extra_hosts: [ 'host.docker.internal:host-gateway' ]
#        restart: always
#        environment:
#            ADMINER_DEFAULT_SERVER: mariadb
#        depends_on:
#            - mariadb
#        ports:
#            - 8888:8080

# credentials: root:password
# http://localhost:8888/?server=mariadb&username=root
