name: elasticsearch
services:
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        environment:
            discovery.type: single-node
        volumes:
            - ./local-data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
