name: elasticsearch
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ./local-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    extra_hosts:
      - host.docker.internal:host-gateway
    profiles:
      - only-elasticsearch
      - all
