name: services
services:
#  DB's
  postgres:
    extends:
      service: postgres
      file: ./postgres/compose.yml

  pgadmin:
    extends:
      service: pgadmin
      file: ./pgadmin/compose.yml

  mysql:
    extends:
      service: mysql
      file: ./mysql/compose.yml

  mariadb:
    extends:
      service: mariadb
      file: ./mariadb/compose.yml

  phpmyadmin:
    extends:
      service: phpmyadmin
      file: ./phpmyadmin/compose.yml

  # INFO: Remember to integrate with keycloak
  rabbitmq:
    extends:
      service: rabbitmq
      file: ./rabbitmq/compose.yml
  # INFO: Remember to integrate with keycloak
  portainer:
    extends:
      service: portainer
      file: ./portainer/compose.yml

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
  pgadmin_cert_data:
  mysql_data:
  mariadb_data:
  rabbitmq_data:

secrets:
  portainer-password:
    file: ./portainer/config/password.txt
