name: services
services:
#  DB's
  postgres:
    extends:
      service: postgres
      file: ./postgres/compose.yml

  pgadmin:
    extends:
      service: pgadmin
      file: ./pgadmin/compose.yml

  rabbitmq:
    extends:
      service: rabbitmq
      file: ./rabbitmq/compose.yml

  portainer:
    extends:
      service: portainer
      file: ./portainer/compose.yml

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
  pgadmin_cert_data:
  rabbitmq_data:

networks:
  rabbitmq:
    driver: bridge

secrets:
  portainer-password:
    file: ./portainer/config/portainerpass.txt
