name: services

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
#  DB's
  postgres:
    extends:
      service: postgres
      logging: *logging
      file: ./postgres/compose.yml

  pgadmin:
    extends:
      service: pgadmin
      file: ./pgadmin/compose.yml

  mysql:
    extends:
      service: mysql
      file: ./mysql/compose.yml

  mariadb:
    extends:
      service: mariadb
      file: ./mariadb/compose.yml

  phpmyadmin:
    extends:
      service: phpmyadmin
      file: ./phpmyadmin/compose.yml

  keycloak:
    extends:
      service: keycloak
      file: ./keycloak/compose.yml

  grafana:
    extends:
      service: grafana
      file: ./grafana/compose.yml

  prometheus:
    extends:
      service: prometheus
      file: ./prometheus/compose.yml

  # INFO: Remember to integrate with keycloak
  rabbitmq:
    extends:
      service: rabbitmq
      file: ./rabbitmq/compose.yml
  # INFO: Remember to integrate with keycloak
  portainer:
    extends:
      service: portainer
      file: ./portainer/compose.yml

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
  pgadmin_cert_data:
  mysql_data:
  mariadb_data:
  rabbitmq_data:

secrets:
  portainer-password:
    file: ./portainer/config/password.txt
