version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    # extra_hosts: ["host.docker.internal:host-gateway"]
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      # - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_db_data_container:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    container_name: adminer
    image: adminer:latest
    # extra_hosts: ["host.docker.internal:host-gateway"]
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8888:8080

volumes:
  mysql_db_data_container:
