services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_container
    ports:
      - "8000:8000"
      - "9443:9443"
    environment:
      TZ: Europe/Yerevan
      USERNAME: "admin"
      PASSWORD: "pa$$w0rd"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always
