name: portainer
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    restart: unless-stopped
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '--admin-password-file=/run/secrets/portainer-password'
    profiles:
      - only-portainer
      - all
    secrets:
      - portainer-password
