name: portainer
services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    command:
      - --admin-password-file=/run/secrets/portainer-password
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - portainer-password
    restart: unless-stopped
    profiles: ["only-portainer", "all"]
