name: rabbitmq
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}
#    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - rabbitmq
